//-- USER --//
//--Login--//
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
//--CheckUserAuth--//
export const USER_CHECK_AUTH_REQUEST = 'USER_CHECK_AUTH_REQUEST';
export const USER_CHECK_AUTH_FAIL = 'USER_CHECK_AUTH_FAIL';
export const USER_CHECK_AUTH_SUCCESS = 'USER_CHECK_AUTH_SUCCESS';
//--LogoutUser--//
export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';
export const USER_LOGOUT_FAIL = 'USER_LOGOUT_FAIL';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';

//--PROVIDERS--//
//--Add Providers--//
export const PROVIDER_ADD_REQUEST = 'PROVIDER_ADD_REQUEST';
export const PROVIDER_ADD_FAIL = 'PROVIDER_ADD_FAIL';
export const PROVIDER_ADD_SUCCESS = 'PROVIDER_ADD_SUCCESS';
//--List--//
export const PROVIDER_LIST_REQUEST = 'PROVIDER_LIST_REQUEST';
export const PROVIDER_LIST_FAIL = 'PROVIDER_LIST_FAIL';
export const PROVIDER_LIST_SUCCESS = 'PROVIDER_LIST_SUCCESS';
//--Delete--//
export const PROVIDER_DELETE_REQUEST = 'PROVIDER_DELETE_REQUEST';
export const PROVIDER_DELETE_FAIL = 'PROVIDER_DELETE_FAIL';
export const PROVIDER_DELETE_SUCCESS = 'PROVIDER_DELETE_SUCCESS';
//--Update--//
export const PROVIDER_UPDATE_REQUEST = 'PROVIDER_UPDATE_REQUEST';
export const PROVIDER_UPDATE_FAIL = 'PROVIDER_UPDATE_FAIL';
export const PROVIDER_UPDATE_SUCCESS = 'PROVIDER_UPDATE_SUCCESS';
//--GET--//
export const PROVIDER_GET_REQUEST = 'PROVIDER_GET_REQUEST';
export const PROVIDER_GET_FAIL = 'PROVIDER_GET_FAIL';
export const PROVIDER_GET_SUCCESS = 'PROVIDER_GET_SUCCESS';

//--MEASURES--//
//--Add Providers--//
export const MEASURE_ADD_REQUEST = 'MEASURE_ADD_REQUEST';
export const MEASURE_ADD_FAIL = 'MEASURE_ADD_FAIL';
export const MEASURE_ADD_SUCCESS = 'MEASURE_ADD_SUCCESS';
//--List--//
export const MEASURE_LIST_REQUEST = 'MEASURE_LIST_REQUEST';
export const MEASURE_LIST_FAIL = 'MEASURE_LIST_FAIL';
export const MEASURE_LIST_SUCCESS = 'MEASURE_LIST_SUCCESS';
//--Delete--//
export const MEASURE_DELETE_REQUEST = 'MEASURE_DELETE_REQUEST';
export const MEASURE_DELETE_FAIL = 'MEASURE_DELETE_FAIL';
export const MEASURE_DELETE_SUCCESS = 'MEASURE_DELETE_SUCCESS';
//--Update--//
export const MEASURE_UPDATE_REQUEST = 'MEASURE_UPDATE_REQUEST';
export const MEASURE_UPDATE_FAIL = 'MEASURE_UPDATE_FAIL';
export const MEASURE_UPDATE_SUCCESS = 'MEASURE_UPDATE_SUCCESS';
//--GET--//
export const MEASURE_GET_REQUEST = 'MEASURE_GET_REQUEST';
export const MEASURE_GET_FAIL = 'MEASURE_GET_FAIL';
export const MEASURE_GET_SUCCESS = 'MEASURE_GET_SUCCESS';

//--PRODUCT--//
//--Add--//
export const PRODUCT_ADD_REQUEST = 'PRODUCT_ADD_REQUEST';
export const PRODUCT_ADD_FAIL = 'PRODUCT_ADD_FAIL';
export const PRODUCT_ADD_SUCCESS = 'PRODUCT_ADD_SUCCESS';
//--List--//
export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
//--Delete--//
export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST';
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
//--Update--//
export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST';
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL';
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS';
//--GET--//
export const PRODUCT_GET_REQUEST = 'PRODUCT_GET_REQUEST';
export const PRODUCT_GET_FAIL = 'PRODUCT_GET_FAIL';
export const PRODUCT_GET_SUCCESS = 'PRODUCT_GET_SUCCESS';
//--ModalFom--//
export const PRODUCT_MODAL = 'PRODUCT_MODAL';
export const PRODUCT_EDIT = 'PRODUCT_EDIT';

//--ORDERS--//
//--List--//
export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST';
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL';
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
//--Add--//
export const ORDER_ADD_REQUEST = 'ORDER_ADD_REQUEST';
export const ORDER_ADD_FAIL = 'ORDER_ADD_FAIL';
export const ORDER_ADD_SUCCESS = 'ORDER_ADD_SUCCESS';
//--Delete--//
export const ORDER_DELETE_REQUEST = 'ORDER_DELETE_REQUEST';
export const ORDER_DELETE_FAIL = 'ORDER_DELETE_FAIL';
export const ORDER_DELETE_SUCCESS = 'ORDER_DELETE_SUCCESS';

//--CHECKOUT--//
//--Add--//
export const  CHECKOUT_ADD_REQUEST = 'CHECKOUT_ADD_REQUEST';
export const  CHECKOUT_ADD_FAIL = 'CHECKOUT_ADD_FAIL';
export const  CHECKOUT_ADD_SUCCESS = 'CHECKOUT_ADD_SUCCESS';
//--List--//
export const  CHECKOUT_LIST_REQUEST = 'CHECKOUT_LIST_REQUEST';
export const  CHECKOUT_LIST_FAIL = 'CHECKOUT_LIST_FAIL';
export const  CHECKOUT_LIST_SUCCESS = 'CHECKOUT_LIST_SUCCESS';
//--Delete--//
export const  CHECKOUT_DELETE_REQUEST = 'CHECKOUT_DELETE_REQUEST';
export const  CHECKOUT_DELETE_FAIL = 'CHECKOUT_DELETE_FAIL';
export const  CHECKOUT_DELETE_SUCCESS = 'CHECKOUT_DELETE_SUCCESS';
//--Get--//
export const  CHECKOUT_GET_REQUEST = 'CHECKOUT_GET_REQUEST';
export const  CHECKOUT_GET_FAIL = 'CHECKOUT_GET_FAIL';
export const  CHECKOUT_GET_SUCCESS = 'CHECKOUT_GET_SUCCESS';
//--Send--//
export const  CHECKOUT_SEND_REQUEST = 'CHECKOUT_SEND_REQUEST';
export const  CHECKOUT_SEND_FAIL = 'CHECKOUT_SEND_FAIL';
export const  CHECKOUT_SEND_SUCCESS = 'CHECKOUT_SEND_SUCCESS';

//--MESSAGE--//
//--Load--//
export const MESSAGE_LOAD_REQUEST = 'MESSAGE_LOAD_REQUEST';
export const MESSAGE_LOAD_FAIL = 'MESSAGE_LOAD_FAIL';
export const MESSAGE_LOAD_SUCCESS = 'MESSAGE_LOAD_SUCCESS';
//--Clear--//
export const MESSAGE_CLEAR_REQUEST = 'MESSAGE_CLEAR_REQUEST';
export const MESSAGE_CLEAR_FAIL = 'MESSAGE_CLEAR_FAIL';
export const MESSAGE_CLEAR_SUCCESS = 'MESSAGE_CLEAR_SUCCESS';